### PR TITLE
Landmarks

### PR DESCRIPTION
**Pull request by vicr123**
This PR adds the display of landmarks

### CODE REVIEW

**Review by Vrabbers — COMMENTED** [review]
I'll have a closer look at the svg rendering in a bit

**Comment by Vrabbers** [comment]
SKSvg.Load() seems to be a relatively heavy operation; we should probably look into caching the loaded assets.

**Review by Royce551 — APPROVED** [review]
LGTM pls fix that one if statement~

**Review by Vrabbers — CHANGES_REQUESTED** [review]
NO!

**Review by Vrabbers — APPROVED** [review]
i am hapy

**Pull request merged**
